package com.hoteles.hrt4e;

import com.hoteles.hrt4e.models.Catalogo;
import com.hoteles.hrt4e.models.ModeloCatalogoProducto;
import com.hoteles.hrt4e.models.CatalogoProducto;
import com.hoteles.hrt4e.utils.Singleton;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.WindowConstants;

/**
 *
 * @author Hacktom
 */
public class InventarioForm extends javax.swing.JFrame {

    
    private ModeloCatalogoProducto modeloR;
    private ModeloCatalogoProducto modeloF;
    private ModeloCatalogoProducto modeloX;
    
    public InventarioForm() {
        initComponents();

        ArrayList<CatalogoProducto> productosR = Singleton.getInstance().getCatalogos().getInventario().getProductosTipo(1);
        modeloR = new ModeloCatalogoProducto();
        modeloR.productos = productosR;
        jTable1.setModel(modeloR);

        ArrayList<CatalogoProducto> productosF = Singleton.getInstance().getCatalogos().getInventario().getProductosTipo(2);
        modeloF = new ModeloCatalogoProducto();
        modeloF.productos = productosF;
        jTable2.setModel(modeloF);

        ArrayList<CatalogoProducto> productosX = Singleton.getInstance().getCatalogos().getInventario().getProductosTipo(3);
        modeloX = new ModeloCatalogoProducto();
        modeloX.productos = productosX;
        jTable3.setModel(modeloX);

    }
    
    private void refreshData(){
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Inventario");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Restaurant", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Farmacia", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("XXX", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton2)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int tabSelected = jTabbedPane5.getSelectedIndex();
        CatalogoProducto cat = new CatalogoProducto();
        if(tabSelected==0){
            cat.setIdCatalogoTipoProducto(1);
        }else if(tabSelected==1){
            cat.setIdCatalogoTipoProducto(2);
        }else {
            cat.setIdCatalogoTipoProducto(3);
        }
        AccionProducto agregarProducto = new AccionProducto(1,cat);
        agregarProducto.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        agregarProducto.setVisible(true);
        agregarProducto.setLocationRelativeTo(null);
        
        agregarProducto.setOnFormResultListener(new FormGeneral.OnFormResultListener() {

            @Override
            public void onFormResult(Object object) {
            
                if(object instanceof CatalogoProducto){
                    CatalogoProducto catalogoProducto = (CatalogoProducto)object;
                    Singleton.getInstance().getCatalogos().getInventario().addProducto(catalogoProducto);
                    if(catalogoProducto.getIdCatalogoTipoProducto()==1){
                        modeloR.productos.add(catalogoProducto);
                        modeloR.fireTableDataChanged();
                    }else if(catalogoProducto.getIdCatalogoTipoProducto()==2){
                        modeloF.productos.add(catalogoProducto);
                        modeloF.fireTableDataChanged();
                    }else if(catalogoProducto.getIdCatalogoTipoProducto()==3){
                        modeloX.productos.add(catalogoProducto);
                        modeloX.fireTableDataChanged();
                    }
                    
                }
                
            }
        });
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int tabSelected = jTabbedPane5.getSelectedIndex();
        
        CatalogoProducto cat;
        if(tabSelected==0){
            cat = modeloR.productos.get(jTable1.getSelectedRow());
        }else if(tabSelected==1){
            cat = modeloF.productos.get(jTable2.getSelectedRow());
        }else {
            cat = modeloX.productos.get(jTable3.getSelectedRow());
        }

        if(cat!=null){
            AccionProducto agregarProducto = new AccionProducto(3,cat);
            agregarProducto.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            agregarProducto.setVisible(true);
            agregarProducto.setLocationRelativeTo(null);

            agregarProducto.setOnFormResultListener(new FormGeneral.OnFormResultListener() {

                @Override
                public void onFormResult(Object object) {

                    if(object instanceof CatalogoProducto){
                        CatalogoProducto catalogoProducto = (CatalogoProducto)object;
                        ArrayList<CatalogoProducto> catSingleton = Singleton.getInstance().getCatalogos().getInventario().getProductos();
                        catSingleton.remove(buscarProductoIndex(catSingleton, catalogoProducto));
                        if(catalogoProducto.getIdCatalogoTipoProducto()==1){
                            modeloR.productos.remove(buscarProductoIndex(modeloR.productos, catalogoProducto));
                            modeloR.fireTableDataChanged();
                        }else if(catalogoProducto.getIdCatalogoTipoProducto()==2){
                            modeloF.productos.remove(buscarProductoIndex(modeloF.productos, catalogoProducto));
                            modeloF.fireTableDataChanged();
                        }else if(catalogoProducto.getIdCatalogoTipoProducto()==3){
                            modeloX.productos.remove(buscarProductoIndex(modeloX.productos, catalogoProducto));
                            modeloX.fireTableDataChanged();
                        }

                    }

                }
            });
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int tabSelected = jTabbedPane5.getSelectedIndex();
        
        CatalogoProducto cat;
        if(tabSelected==0){
            cat = modeloR.productos.get(jTable1.getSelectedRow());
        }else if(tabSelected==1){
            cat = modeloF.productos.get(jTable2.getSelectedRow());
        }else {
            cat = modeloX.productos.get(jTable3.getSelectedRow());
        }
        
        if(cat!=null){
            AccionProducto agregarProducto = new AccionProducto(2,cat);
            agregarProducto.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            agregarProducto.setVisible(true);
            agregarProducto.setLocationRelativeTo(null);

            agregarProducto.setOnFormResultListener(new FormGeneral.OnFormResultListener() {

                @Override
                public void onFormResult(Object object) {

                    if(object instanceof CatalogoProducto){
                        CatalogoProducto catalogoProducto = (CatalogoProducto)object;
                        ArrayList<CatalogoProducto> catSingleton = Singleton.getInstance().getCatalogos().getInventario().getProductos();
                        catSingleton.set(buscarProductoIndex(catSingleton, catalogoProducto),catalogoProducto);
                        if(catalogoProducto.getIdCatalogoTipoProducto()==1){
                          
                            modeloR.productos.set(buscarProductoIndex(modeloR.productos, catalogoProducto), catalogoProducto);
                            modeloR.fireTableDataChanged();
                        }else if(catalogoProducto.getIdCatalogoTipoProducto()==2){
                    
                            modeloF.productos.set(buscarProductoIndex(modeloF.productos, catalogoProducto), catalogoProducto);
                            modeloF.fireTableDataChanged();
                        }else if(catalogoProducto.getIdCatalogoTipoProducto()==3){
                            
                            modeloX.productos.set(buscarProductoIndex(modeloX.productos, catalogoProducto), catalogoProducto);
                            modeloX.fireTableDataChanged();
                        }

                    }

                }
            });
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private int buscarProductoIndex(ArrayList<CatalogoProducto> lista,CatalogoProducto catalogoProducto){
        
        for(int i = 0;i<lista.size();i++){
            if(lista.get(i).getId()==catalogoProducto.getId()){
                return i;
            }
        }
        return -1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
